IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SPEC')
BEGIN
EXEC('CREATE SCHEMA SPEC')
END
-- all the drops statements
IF OBJECT_ID('SPEC.SPEC_QUIC_Billholds') IS NOT NULL DROP TABLE SPEC.SPEC_QUIC_Billholds
IF OBJECT_ID('SPEC.SPEC_STAT_Workgroup_Specs') IS NOT NULL DROP TABLE SPEC.SPEC_STAT_Workgroup_Specs
IF OBJECT_ID('SPEC.SPEC_STAT_Worklist_Specs') IS NOT NULL DROP TABLE SPEC.SPEC_STAT_Worklist_Specs